name: Demande RGPD (DSR)
description: Demande d'accès, rectification ou suppression
title: "[DSR] "
labels: ["rgpd"]
body:
  - type: textarea
    id: request
    attributes:
      label: Détails de la demande
    validations:
      required: true
